force-app/main/default/objects/Trust__c/Trust__c.object-meta.xml
<CustomObject>
    <description>A Trust Escrow account that belongs to a specific account for billing</description>
    <label>Trust</label>
    <nameField>
        <label>Trust Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trusts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trust__c/fields/File_Number__c.field-meta.xml
<CustomField>
    <fullName>File_Number__c</fullName>
    <description>File number that is related to the trust</description>
    <label>File Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trust__c/fields/Trusts_Account__c.field-meta.xml
<CustomField>
    <fullName>Trusts_Account__c</fullName>
    <description>The Account that the escrow is for</description>
    <label>Trust&apos;s Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trusts</relationshipLabel>
    <relationshipName>Trusts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trust__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retainer</fullName>
            </value>
            <value>
                <fullName>Buyer Desposit</fullName>
            </value>
            <value>
                <fullName>Escrow Holdback</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
                <isActive>false</isActive>
                <label>Real Estate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trust_Line_Item__c/Trust_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Trust Line Item</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trust Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trust_Line_Item__c/fields/Billable_Rate__c.field-meta.xml
<CustomField>
    <fullName>Billable_Rate__c</fullName>
    <label>Billable Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trust_Line_Item__c/fields/Hours_Billed__c.field-meta.xml
<CustomField>
    <fullName>Hours_Billed__c</fullName>
    <label>Hours Billed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trust_Line_Item__c/fields/Trust__c.field-meta.xml
<CustomField>
    <fullName>Trust__c</fullName>
    <label>Trust</label>
    <referenceTo>Trust__c</referenceTo>
    <relationshipLabel>Trust Line Items</relationshipLabel>
    <relationshipName>Trust_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trust_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Bill</fullName>
                <default>true</default>
                <label>Bill</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TrustController_Test.cls
@IsTest
public class TrustController_Test {

    @TestSetup
    static void makeData(){
        Account testAccount = new Account();
        testAccount.Account_Email__c = 'fake@email.com';
        testAccount.Name = 'TestName';
        insert testAccount;

        Trust__c t = new Trust__c();
        t.File_Number__c = 123;
        t.Trusts_Account__c = testAccount.Id;
        insert t;

        Trust_Line_Item__c tli_dep = new Trust_Line_Item__c();
        tli_dep.Deposit__c = 10000;
        tli_dep.Type__c = 'Deposit';
        tli_dep.Trust__c = t.Id;
        insert tli_dep;

        Trust_Line_Item__c tli_bill = new Trust_Line_Item__c();
        tli_bill.Billable_Rate__c = 15;
        tli_bill.Hours_Billed__c = 4;
        tli_bill.Type__c = 'Bill';
        tli_bill.Trust__c = t.Id;
        insert tli_bill;
    }

    static testMethod void billingSendEmail() {
        Trust__c trust = [SELECT Id FROM Trust__c][0];
        BillingController.SendBillingEmail(trust.id);
    }

    static testMethod void getTrustItems() {
        Trust__c trust = [SELECT Id FROM Trust__c][0];
        List<Trust_Line_Item__c> result = TrustLineItemSummaryController.RetriveTrustLineItems(trust.id);

        system.assert(result.size() == 2);
    }
}