force-app/main/default/objects/Trust__c/Trust__c.object-meta.xml
<CustomObject>
    <description>A Trust Escrow account that belongs to a specific account for billing</description>
    <label>Trust</label>
    <nameField>
        <label>Trust Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trusts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trust__c/fields/File_Number__c.field-meta.xml
<CustomField>
    <fullName>File_Number__c</fullName>
    <description>File number that is related to the trust</description>
    <label>File Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trust__c/fields/Total_Amount_In_Escrow__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_In_Escrow__c</fullName>
    <label>Total Amount In Escrow</label>
    <summarizedField>Trust_Line_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Trust_Line_Item__c.Trust__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Trust__c/fields/Trusts_Account__c.field-meta.xml
<CustomField>
    <fullName>Trusts_Account__c</fullName>
    <description>The Account that the escrow is for</description>
    <label>Trust&apos;s Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trusts</relationshipLabel>
    <relationshipName>Trusts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BillingController.cls
public with sharing class BillingController {   
    @AuraEnabled
    public static void SendBillingEmail(Id TrustId) {
        system.debug(TrustId);
        Trust__c trust = GetTrustRecord(TrustId);
        system.debug(trust);

        String userName = UserInfo.getUserName();
        User activeUser = [Select Email From User where Username = : userName limit 1];
        String userEmail = activeUser.Email;
        String accountEmail = trust.Trusts_Account__r.Account_Email__c;

        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.toAddresses = new List<string> { accountEmail };
        message.setReplyTo(userEmail);
        message.optOutPolicy = 'FILTER';
        message.subject = 'You have been billed';
        message.plainTextBody = FormatEmailBodyFromTrustRecord(trust);
        Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
        Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
    }

    private static string FormatEmailBodyFromTrustRecord(Trust__c Trust){
        return 'You have ' + Trust.Total_Amount_In_Escrow__c + ' left in your escrow account: ' + Trust.File_Number__c;
    }
    
    private static Trust__c GetTrustRecord(Id TrustId){    
        Trust__c trust =  [SELECT Total_Amount_In_Escrow__c, Trusts_Account__r.Account_Email__c, File_Number__c
                FROM Trust__c
                WHERE Id = :TrustId];
        
        return trust;
    }
}