force-app/main/default/objects/Trust__c/Trust__c.object-meta.xml
<CustomObject>
    <description>A Trust Escrow account that belongs to a specific account for billing</description>
    <label>Trust</label>
    <nameField>
        <label>Trust Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trusts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trust_Line_Item__c/Trust_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Trust Line Item</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trust Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trust_Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Deposit__c - (Billable_Rate__c  *  Hours_Billed__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trust_Line_Item__c/fields/Billable_Rate__c.field-meta.xml
<CustomField>
    <fullName>Billable_Rate__c</fullName>
    <label>Billable Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trust_Line_Item__c/fields/Hours_Billed__c.field-meta.xml
<CustomField>
    <fullName>Hours_Billed__c</fullName>
    <label>Hours Billed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trust_Line_Item__c/fields/Processing_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Processing_Date_Time__c</fullName>
    <label>Processing Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trust_Line_Item__c/fields/Trust__c.field-meta.xml
<CustomField>
    <fullName>Trust__c</fullName>
    <label>Trust</label>
    <referenceTo>Trust__c</referenceTo>
    <relationshipLabel>Trust Line Items</relationshipLabel>
    <relationshipName>Trust_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TrustLineItemSummaryController.cls
public class TrustLineItemSummaryController {

    @AuraEnabled(cacheable=true)
    public static List<Trust_Line_Item__c> RetriveTrustLineItems(Id TrustId) {
        List<Trust_Line_Item__c> linesItemsForTrust = new List<Trust_Line_Item__c>();

        if(Schema.sObjectType.Trust_Line_Item__c.isAccessible()){
            linesItemsForTrust = [SELECT Id, Amount__c, Billable_Rate__c, 
                        Deposit__c, Hours_Billed__c, Name, Processing_Date_Time__c, Description__c
                    FROM Trust_Line_Item__c
                    WHERE Trust__c = :TrustId
                    ORDER BY Processing_Date_Time__c DESC];
        }
        return linesItemsForTrust;        
    }
}